### ISSUE TITLE
Can't download:HTTP error 404.

### ISSUE THREAD

**Issue by barveaditya** [johnmackintosh/rockthemes#13]
I love the palettes you have. However, ON doing 
remotes::install_github('johnmackintosh/rockthemes')

I keep getting the following: 
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref master

  Did you spell the repo owner (`johnmackintosh`) and repo name (`rockthemes`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

**Comment by StatsGary** [comment]
Do you have the remotes package installed in R?

**Comment by johnmackintosh** [comment]
Hi, thanks for your comments :)

Looks like remotes is trying to install from the master branch.

Unfortunately, there is no 'master' branch, it's 'main'.

If you update to the latest version of the {remotes} package, it should find the 'main' branch.

See :
https://twitter.com/grrrck/status/1350504524901920773?s=19

Alternatively
remotes::install_github('johnmackintosh/rockthemes@main')

**Comment by barveaditya** [comment]
@johnmackintosh .. perfect .. that worked. 

However, something occurred to me after is that I need to make a continuous color gradient, and that could not! :( Rather, I do not now how to convert a 10 color scale to a continuous one (_n_ = 256). Any help would be great! Rock and metal has place in science! ;)

**Comment by johnmackintosh** [comment]
@barveaditya 
Do you have a reprex you could share?

I can get something to work with the standard 4 colour palettes:

```r

library(ggplot2)
library(rockthemes)
 
df <- data.frame(
  x = runif(1000),
  y = runif(1000),
  z1 = rnorm(1000),
  z2 = abs(rnorm(1000)),
  temp = c(1:999, by = 1)
)
 
 
ggplot(df, aes(x, y)) +
  geom_point(aes(colour = temp)) +
  scale_colour_gradientn(colours = rock_palette('nodoubt', 
                                                256, 
                                                type = 'continuous'))



```

**Comment by johnmackintosh** [comment]
```r
ggplot(df, aes(x, y)) +
+     geom_point(aes(colour = temp)) +
+     scale_colour_deelite(type = 'continuous')



```

**Comment by johnmackintosh** [comment]
![image](https://user-images.githubusercontent.com/3278367/105543977-5900d580-5cf2-11eb-95fe-f161ec8dfe66.png)

**Comment by barveaditya** [comment]
@johnmackintosh oh that does it, than you very much. Thanks for all the help! :)

**Comment by johnmackintosh** [comment]
closing this one, but need to tweak the individual palettes  so #14 awaits
