### ISSUE TITLE
Proposing deelite groove is in the heart

### ISSUE THREAD

**Issue by richardi7** [johnmackintosh/rockthemes#4]
I would like to propose deelite groove is in the heart not an album but great colours 
https://upload.wikimedia.org/wikipedia/en/7/7b/Deee-Lite_%E2%80%93_Groove_Is_In_The_Heart_single_cover.png

Not sure if I am doing it all right - still trying to understand all of this git stuff! 

I was not sure if I had to raise an issue for you to give me an git auth_token

**Comment by johnmackintosh** [comment]
Hi, that is cool. I just didn't want to get swamped with requests for metal albums 😄.

This is a great cover and I am looking forward to seeing the resulting palettes..go for it 👍

**Comment by richardi7** [comment]
I am wondering if the create_from_github the fork should be set to FALSE
not TRUE? 
I was getting this 

> usethis::create_from_github("johnmackintosh/rockthemes", fork = TRUE) 
Error: No GitHub `auth_token` is available. 
See `browse_github_token()` for help storing a token as an environment
variable.

from help it suggested changing it to FALSE to get around this error 
fork 
If TRUE, we create and clone a fork. If FALSE, we clone repo_spec
itself. Will be set to FALSE if no auth_token (a.k.a. PAT) is provided
or preconfigured.  

changing it to FALSE 
> usethis::create_from_github("johnmackintosh/rockthemes", fork = FALSE) 
Which git protocol to use? (enter 0 to exit)  

1: ssh   <-- presumes that you have set up ssh keys 
2: https <-- choose this if you don't have ssh keys (or don't know if
you do) 

Selection: 2 
* Tip: To suppress this menu in future, put 
  `options(usethis.protocol = "https")` 
  in your script or in a user- or project-level startup file,
'.Rprofile'. 
  Call `usethis::edit_r_profile()` to open it for editing. 
√ Cloning repo from 'https://github.com/johnmackintosh/rockthemes.git'
into 'C:/Users/rcw_s/rockthemes' 
√ Setting active project to 'C:/Users/rcw_s/rockthemes' 
√ Opening 'C:/Users/rcw_s/rockthemes/' in new RStudio session 
√ Setting active project to '<no active project>' 

This then downloaded the package

---
Richard Wilson 
Director
i7 Analytics

On 21/10/2020 21:03, John MacKintosh wrote:

> Hi, that is cool. I just didn't want to get swamped with requests for metal albums 😄. 
> 
> This is a great cover and I am looking forward to seeing the resulting palettes..go for it 👍 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/johnmackintosh/rockthemes/issues/4#issuecomment-713841830
[2]

**Comment by johnmackintosh** [comment]
It should work OK if you have configured RStudio and git to connect with each other. 
If you haven't done this, (or aren't sure), search for Jenny Bryan's 'Happy Git with R', and work through that. 
You can fork the repo manually in GitHub itself, but you will still need to connect RStudio up to your GitHub account, as per Jenny's guide.
If you are struggling/ don't have time for it, then you could always just submit the values for your 4/ 10 colour palettes here, and I'll add them in and credit you

**Comment by johnmackintosh** [comment]
Hi Richard, thanks, that's been added in now. 
Lots of colour  there 💯
